import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'app/home_shell.dart';
import 'features/auth/auth.dart';
import 'l10n/generated/app_localizations.dart';
import 'shared/app_messenger.dart';
import 'shared/config/emulator_config.dart';
import 'firebase_options.dart';
import 'shared/config/firebase_options_demo.dart';
import 'shared/services/locale_controller.dart';
import 'shared/theme/app_theme.dart';
import 'features/billing/ads/ad_backdrop.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Which Firebase project this build talks to.
  //
  // The emulator suite only accepts a `demo-` prefixed project (that prefix
  // is what tells the Firebase tooling a project is fake and must never
  // reach real infrastructure), so local development cannot use the real
  // options -- and a release build must never use the demo ones, which point
  // at a project that does not exist.
  //
  // `firebase_options.dart` is generated by `flutterfire configure` and is
  // gitignored, so a fresh clone has to run that command before it will
  // compile. See docs/FIREBASE_SETUP_GUIDE.md.
  //
  // Must straddle initializeApp: on web, Auth requests can only be diverted
  // to the emulator before it; Firestore and Storage only after it.
  prepareFirebaseEmulatorsIfEnabled();
  await Firebase.initializeApp(
    options: useFirebaseEmulator
        ? demoFirebaseOptions
        : DefaultFirebaseOptions.currentPlatform,
  );
  await connectToFirebaseEmulatorsIfEnabled();

  runApp(const WanoteApp());
}

/// Root widget: wires the app-wide [AuthController] via `provider` and hands
/// the real app shell ([HomeShell]) to [LaunchGateScreen] as its
/// `homeBuilder`, so LaunchGateScreen keeps handling sign-in / biometric
/// gate / forced onboarding (first pet profile) before anything in
/// `lib/app/` is ever reached.
class WanoteApp extends StatelessWidget {
  const WanoteApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AuthController>(
          create: (_) {
            final authRepository = FirebaseAuthRepository();
            return AuthController(
              authRepository: authRepository,
              userAccountRepository: FirestoreUserAccountRepository(),
              petProfileRepository: FirestorePetProfileRepository(),
              biometricService: LocalAuthBiometricService(),
              accountDeletionService: DefaultAccountDeletionService(
                authRepository: authRepository,
                fileEraser: StorageAccountFileEraser(),
                documentEraser: FirestoreAccountDocumentEraser(),
                backendClient: AccountBackendClient.fromEnvironment(),
              ),
            )..initialize();
          },
        ),
        ChangeNotifierProvider<LocaleController>(
          create: (_) => LocaleController(),
        ),
      ],
      child: Consumer<LocaleController>(
        builder: (context, localeController, _) => MaterialApp(
          title: 'wanote',
          // Lets a message outlive the screen that produced it -- see
          // shared/app_messenger.dart for the case that needs it.
          scaffoldMessengerKey: appMessengerKey,
          // Lets AdBackdrop reach the overlay: an interstitial outlives
          // the frame that triggered it, so the code covering the app
          // behind it has no BuildContext of its own.
          navigatorKey: appNavigatorKey,
          theme: buildWanoteTheme(),
          // Shipaton targets a global audience (spec section on i18n), so
          // UI text follows the device's own language setting by default
          // rather than the App/Play Store account's billing region -- see
          // the PM conversation this was scoped from for why store region
          // isn't a reliable signal for language preference. `locale` is
          // left null (falls back to system locale resolution) unless the
          // user picked an explicit override via LanguageIconButton /
          // showLanguagePicker (sign-in screen, settings screen). Only
          // en/ja are translated so far (infra + sign-in/settings screens
          // as the model case); everything else still falls back to
          // whatever's hardcoded until migrated screen-by-screen.
          locale: localeController.locale,
          localizationsDelegates: AppLocalizations.localizationsDelegates,
          supportedLocales: AppLocalizations.supportedLocales,
          home: LaunchGateScreen(
            homeBuilder: (context) {
              final controller = context.watch<AuthController>();
              final uid = controller.currentUser?.uid;
              final activePet = controller.activePet;

              // Defensive fallbacks only: LaunchGateScreen already
              // guarantees a signed-in user with at least one pet before it
              // ever calls homeBuilder (see its `gateAction == enterApp` /
              // `pets.isEmpty` checks in launch_gate_screen.dart). These
              // branches guard against a narrow race (e.g. the active pet
              // being deleted out from under the stream) rather than
              // assuming it can never happen.
              if (uid == null) {
                return const SignUpScreen();
              }
              if (activePet == null) {
                return const PetProfileFormScreen();
              }
              // Keyed per sign-in, not per account.
              //
              // Flutter otherwise reuses the same State when the tree
              // switches back to a HomeShell, and the shell reopens on
              // whichever tab the last session left it on -- 設定, since
              // that is where sign-out lives. Keying on the uid alone did
              // not fix it: signing back in to the same account yields the
              // same key, which is the case the PM actually hit
              // (2026-08-16). The generation counter changes on every
              // claim, so each sign-in gets a shell of its own.
              return HomeShell(
                key: ValueKey('$uid#${controller.sessionGeneration}'),
                uid: uid,
                activePet: activePet,
              );
            },
          ),
        ),
      ),
    );
  }
}
